CREATE TABLE IF NOT EXISTS credit_card_transactions (
"Unnamed: 0" INTEGER,
"trans_date_trans_time" TEXT,
"cc_num" BIGINT,
"merchant" TEXT,
"category" TEXT,
"amt" FLOAT,
"first" TEXT,
"last" TEXT,
"gender" TEXT,
"street" TEXT,
"city" TEXT,
"state" TEXT,
"zip" INTEGER,
"lat" FLOAT,
"long" FLOAT,
"city_pop" INTEGER,
"job" TEXT,
"dob" TEXT,
"trans_num" TEXT,
"unix_time" INTEGER,
"merch_lat" FLOAT,
"merch_long" FLOAT,
"is_fraud" SMALLINT,
"merch_zipcode" FLOAT
);